version: '3.4'

services:
  legislation.api:
    image: ${DOCKER_REGISTRY-}legislationapi
    build:
      context: .
      dockerfile: Legislation.Api/Dockerfile

  voting.api:
    image: ${DOCKER_REGISTRY-}votingapi
    build:
      context: .
      dockerfile: Voting.Api/Dockerfile

  results.api:
    image: ${DOCKER_REGISTRY-}resultsapi
    build:
      context: .
      dockerfile: Results.Api/Dockerfile

